/* eslint-disable eol-last */
export const RECEOVE_ADDRESS = 'receive_address'
export const RECEOVE_CATEGORYS = 'receive_categorys'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USERINFO = 'receive_userinfo'
export const RECEIVE_SHOP_INFO = 'receive_shop_info'
export const RECEIVE_SHOP_GOODS = 'receive_shop_goods'
export const RECEIVE_SHOP_RATINGS = 'receive_shop_ratings'
export const INCREASE_FOOD_COUNT = 'increase_food_count'
export const DECREASE_FOOD_COUNT = 'decrease_food_count'
export const CLEAR_CART = 'clear_cart'